### ISSUE TITLE
unable to fetch alerts from github

### ISSUE THREAD

**Issue by roimor** [github/ghas-jira-integration#24]
Hey there,
Having a lot of issues with fetching the alerts from my repo. (in Github Cloud Enterprise)
the error i keep getting:
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/<org-name>/<repo-name>/secret-scanning/alerts?per_page=100
```

i tried running curl locally with GITHUB_TOKEN exported and it worked. 

here's the action.yml (tried a few variants)
```
jobs:
  jira-sync:
    name: Jira Sync
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
#    needs: [ analyze ]
    steps:
      - name: Sync alerts to Jira issues
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'http://<org>.atlassian.net'
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_user: 'myuser'
          jira_project: 'myproject'
          jira_labels: 'code-scanning'
          sync_direction: 'gh2jira'
```
