### ISSUE TITLE
403 when accessing secret scanning alerts 

### ISSUE THREAD

**Issue by sennap** [github/ghas-jira-integration#27]
I was able to run this action/post jira issues just fine when my repo was public (thus no secret scanning alerts), but once I switch to public and run this in the octodemo org, I get this error:

`DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/octodemo/sennap-ghas-jira/secret-scanning/alerts?per_page=100 HTTP/1.1" 403 None`

fulls logs including `SecurityEvents: write` permission for my GitHub_token: 
[logs_14.zip](https://github.com/github/ghas-jira-integration/files/7644425/logs_14.zip)

workflow file in case you don't have access to the octodemo org:

```
name: "Sync GHAS to Jira"

on: workflow_dispatch
# on:
#   schedule:
#     - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://githubtraining.atlassian.net/'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'SGJ'
          sync_direction: 'gh2jira'
```

secret scanning alert that I can see in the UI as org admin: 
<img width="935" alt="Screen Shot 2021-12-02 at 7 55 42 PM" src="https://user-images.githubusercontent.com/1704143/144485333-46b97db7-9894-4a27-aa42-0d01b3c08f33.png">

cc @cmboling @zbazztian as I saw you added secret scanning support recently 🙏🏻
